### ISSUE TITLE
`ffq` does not work for some low-number SRRs

### ISSUE THREAD

**Issue by jbloom** [pachterlab/ffq#16] opened 2021-07-23 13:38 UTC
I'm not sure if this is expected behavior, but `ffq` does not work for some low-number SRRs. For instance, `ffq SRR038165` gives
```
[2021-07-23 06:33:59,377]    INFO Parsing run SRR038165
[2021-07-23 06:34:02,904]   ERROR 400 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRS011879,SRS024956-SRS025194/
```
despite the fact that `SRR038165` is a valid SRR: https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR038165

**Comment by agalvezm** [comment] 2022-02-10 21:42
Hello! Our apologies for the delay in the response. I looked into the error and it does not seem to be caused by the fact that it is a low-number SRR. Instead, the error arises because there are multiple SRS ids that are associated with that SRR. We have fixed this issue and made lots of improvements to `ffq` in the `devel` branch of the repository, which will be merged with master soon. We have also implemented different test cases to make the tool more robust and avoid this sort of issues. Thanks so much for using `ffq` and feel free to ask any other questions you may have! :)

**Comment by sbooeshaghi** [comment] 2022-04-23 23:49
Hi @jbloom this issue has been fixed and merged into the `master` branch. An updated version of `ffq` can be install with 

```bash
pip install git+https://github.com/pachterlab/ffq
```

and the accession can be fetched with 

```bash
ffq SRR038165
```

We plan on creating an official release (and updating the package on pip) soon. Thank you for bringing this accession to our attention!

**Closed by sbooeshaghi** 2022-04-23 23:49 UTC
